[package]
name = "sticker-infra"
version = "0.1.0"
edition = "2024"

[dependencies]
sticker-core = { workspace = true }
rusqlite = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
rstest = { workspace = true }
